[2022-08-30T02:25:09.326+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2022-08-30T02:25:09.363+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.populate_pet_table scheduled__2020-02-02T00:00:00+00:00 [queued]>
[2022-08-30T02:25:09.363+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-30T02:25:09.363+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-08-30T02:25:09.364+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-30T02:25:09.431+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): populate_pet_table> on 2020-02-02 00:00:00+00:00
[2022-08-30T02:25:09.458+0000] {standard_task_runner.py:52} INFO - Started process 111 to run task
[2022-08-30T02:25:09.478+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'populate_pet_table', 'scheduled__2020-02-02T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_dag.py', '--cfg-path', '/tmp/tmpf2xetaiv', '--error-file', '/tmp/tmpdybi77_0']
[2022-08-30T02:25:09.478+0000] {standard_task_runner.py:80} INFO - Job 16: Subtask populate_pet_table
[2022-08-30T02:25:09.717+0000] {task_command.py:371} INFO - Running <TaskInstance: postgres_operator_dag.populate_pet_table scheduled__2020-02-02T00:00:00+00:00 [running]> on host 7f44611b6b02
[2022-08-30T02:25:09.902+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=populate_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2022-08-30T02:25:09.992+0000] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-08-30T02:25:10.030+0000] {sql.py:315} INFO - Running statement: INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne'), parameters: None
[2022-08-30T02:25:10.040+0000] {sql.py:324} INFO - Rows affected: 1
[2022-08-30T02:25:10.111+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=populate_pet_table, execution_date=20200202T000000, start_date=20220830T022509, end_date=20220830T022510
[2022-08-30T02:25:10.246+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-30T02:25:10.425+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
